### ISSUE TITLE
changelog is missing

### ISSUE THREAD

**Issue by oshanz** [knapo/a9n#16]
I want to update from old a9n version. but there is no release note to plan the migration.
please add a release note. and breaking changes like dropped ruby version support.

**Comment by knapo** [comment]
What a9n and ruby version you're currently running ?

**Comment by oshanz** [comment]
I'm using ruby 2.4 and a9n 0.5.4

**Comment by knapo** [comment]
I think you should first upgrade ruby to 2.5 since 2.4 is [ending its life soon (2020-03-31)](https://www.ruby-lang.org/en/downloads/branches/).  IMO there is no point in upgrading gems and running dead or almost dead ruby version.
You can generate changelog and diff between versions via Release tab, e.g. https://github.com/knapo/a9n/compare/v0.5.4...v1.2.1
So if you can't upgrade ruby to 2.5, try upgrading a9n to 0.8.3 which is the last version supporting ruby 2.4. Let me know if you have any troubles.
